name = "Reseau"
uuid = "802f3686-a58f-41ce-bb0c-3c43c75bba36"
version = "1.1.1"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
EnumX = "4e289a0a-7415-4d19-859d-a7e5c4648b56"
ScopedValues = "7e506255-f358-4e82-b7e4-beb19740aa63"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
julia = "1.11"
EnumX = "1"
ScopedValues = "1"
PrecompileTools = "1"

[weakdeps]
s2n_tls_jll = "cddc5d3d-934d-5d3a-9747-62fc12ea3f48"

[extensions]
ReseauS2NExt = ["s2n_tls_jll"]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
s2n_tls_jll = "cddc5d3d-934d-5d3a-9747-62fc12ea3f48"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
JuliaC = "acedd4c2-ced6-4a15-accc-2607eb759ba2"

[targets]
test = ["Test", "Libdl", "s2n_tls_jll", "Random", "SHA", "JuliaC"]
