name = "Reseau"
uuid = "802f3686-a58f-41ce-bb0c-3c43c75bba36"
version = "1.1.1"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
EnumX = "4e289a0a-7415-4d19-859d-a7e5c4648b56"
LibAwsCal = "ef519ef6-af43-41a0-8ac4-eb81328190af"
LibAwsCommon = "c6e421ba-b5f8-4792-a1c4-42948de3ed9d"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ScopedValues = "7e506255-f358-4e82-b7e4-beb19740aa63"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
aws_lc_jll = "97bc56f7-b146-5eb0-9ba6-f74d48471a93"
s2n_tls_jll = "cddc5d3d-934d-5d3a-9747-62fc12ea3f48"

[extensions]
ReseauS2NExt = ["aws_lc_jll", "s2n_tls_jll"]

[compat]
EnumX = "1"
LibAwsCal = "1.1.12"
LibAwsCommon = "1.3.1"
ScopedValues = "1"
aws_lc_jll = "1.67.0"
julia = "1.11"
s2n_tls_jll = "1.7.0"

[extras]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
aws_lc_jll = "97bc56f7-b146-5eb0-9ba6-f74d48471a93"
s2n_tls_jll = "cddc5d3d-934d-5d3a-9747-62fc12ea3f48"

[targets]
test = ["Test", "Libdl", "aws_lc_jll", "s2n_tls_jll", "Random", "SHA"]
