name = "AwsIO"
uuid = "4047365c-aa37-44ec-b1fa-4c0d5495ccf1"
version = "1.1.1"

[deps]
LibAwsCommon = "c6e421ba-b5f8-4792-a1c4-42948de3ed9d"
LibAwsCal = "ef519ef6-af43-41a0-8ac4-eb81328190af"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[compat]
julia = "1.9"
LibAwsCal = "1.1.12"
LibAwsCommon = "1.3.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
